language: java
jdk:
  - openjdk7
  - openjdk8
services:
  - postgresql
before_install:
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-en_GB
script:
  - "mvn site"
